describe("haft.detection", function()
  local detection = require("haft.detection")
  local config = require("haft.config")

  before_each(function()
    config.reset()
    config.setup({})
    detection.clear_cache()
  end)

  describe("find_project_root", function()
    it("returns nil when detection is disabled", function()
      config.setup({ detection = { enabled = false } })
      local root = detection.find_project_root("/some/path")
      assert.is_nil(root)
    end)

    it("returns nil when no patterns match", function()
      local root = detection.find_project_root("/tmp")
      assert.is_nil(root)
    end)
  end)

  describe("is_haft_project", function()
    it("returns false when not in a project", function()
      local original_cwd = vim.fn.getcwd()
      vim.cmd("cd /tmp")
      detection.clear_cache()
      local result = detection.is_haft_project()
      vim.cmd("cd " .. original_cwd)
      assert.is_false(result)
    end)
  end)

  describe("get_project_root", function()
    it("caches the result", function()
      detection._cached_root = "/cached/root"
      local root = detection.get_project_root()
      assert.equals("/cached/root", root)
    end)
  end)

  describe("get_project_info", function()
    it("returns nil when not in a project", function()
      detection._cached_root = nil
      local original_cwd = vim.fn.getcwd()
      vim.cmd("cd /tmp")
      detection.clear_cache()
      local info = detection.get_project_info()
      vim.cmd("cd " .. original_cwd)
      assert.is_nil(info)
    end)

    it("returns cached info", function()
      detection._cached_root = "/test/project"
      detection._cached_info = { root = "/test/project", name = "project", type = "maven" }
      local info = detection.get_project_info()
      assert.equals("project", info.name)
      assert.equals("maven", info.type)
    end)
  end)

  describe("_detect_project_type", function()
    it("detects haft project type", function()
      local tmpdir = vim.fn.tempname()
      vim.fn.mkdir(tmpdir, "p")
      vim.fn.writefile({}, tmpdir .. "/.haft.yaml")
      local type = detection._detect_project_type(tmpdir)
      vim.fn.delete(tmpdir, "rf")
      assert.equals("haft", type)
    end)

    it("detects maven project type", function()
      local tmpdir = vim.fn.tempname()
      vim.fn.mkdir(tmpdir, "p")
      vim.fn.writefile({}, tmpdir .. "/pom.xml")
      local type = detection._detect_project_type(tmpdir)
      vim.fn.delete(tmpdir, "rf")
      assert.equals("maven", type)
    end)

    it("detects gradle project type", function()
      local tmpdir = vim.fn.tempname()
      vim.fn.mkdir(tmpdir, "p")
      vim.fn.writefile({}, tmpdir .. "/build.gradle")
      local type = detection._detect_project_type(tmpdir)
      vim.fn.delete(tmpdir, "rf")
      assert.equals("gradle", type)
    end)

    it("detects gradle-kts project type", function()
      local tmpdir = vim.fn.tempname()
      vim.fn.mkdir(tmpdir, "p")
      vim.fn.writefile({}, tmpdir .. "/build.gradle.kts")
      local type = detection._detect_project_type(tmpdir)
      vim.fn.delete(tmpdir, "rf")
      assert.equals("gradle-kts", type)
    end)

    it("returns unknown for unrecognized projects", function()
      local tmpdir = vim.fn.tempname()
      vim.fn.mkdir(tmpdir, "p")
      local type = detection._detect_project_type(tmpdir)
      vim.fn.delete(tmpdir, "rf")
      assert.equals("unknown", type)
    end)
  end)

  describe("clear_cache", function()
    it("clears cached values", function()
      detection._cached_root = "/some/root"
      detection._cached_info = { name = "test" }
      detection.clear_cache()
      assert.is_nil(detection._cached_root)
      assert.is_nil(detection._cached_info)
    end)
  end)

  describe("refresh", function()
    it("clears cache and returns new info", function()
      detection._cached_root = "/old/root"
      detection._cached_info = { name = "old" }
      local original_cwd = vim.fn.getcwd()
      vim.cmd("cd /tmp")
      local info = detection.refresh()
      vim.cmd("cd " .. original_cwd)
      assert.is_nil(info)
      assert.is_nil(detection._cached_root)
    end)
  end)
end)
